In [22]:
import numpy as np
import math

# matrix_vector_dot_product

In [ ]:

def matrix_dot_vector(a: list[list[int|float]], b: list[int|float]) -> list[int|float]:
	# Return a list where each element is the dot product of a row of 'a' with 'b'.
	# If the number of columns in 'a' does not match the length of 'b', return -1.
	if len(a[0])!=len(b):
		return -1
	else:
		return np.dot(a,b)


## how does dot product work 

### <img src="../img/img_1.png" width="500" height="500">

In [3]:
a = [[1, 2], [2, 4]]
b = [[1, 2], [4, 5]]
np.dot(a, b)

array([[ 9, 12],
       [18, 24]])

In [6]:
a = [[1, 2], [2, 4]]
b = [[1, 2, 3], [4, 5, 6]]


np.dot(a, b)

array([[ 9, 12, 15],
       [18, 24, 30]])

# Reshape Matrix
## how does reshape works 
- .reshape(2, 3) You're asking NumPy to reshape the array to shape (2, 3) — i.e., 2 rows and 3 columns.
- Reshape does not change the data, only how it's grouped.
- NumPy will flatten the original matrix row-wise:
- Original data: [1, 2, 2, 4, 2, 3]

In [9]:
a = [[1, 2], [2, 4], [2,3]]
matrix = np.array(a).reshape(2, 3)  # 2 rows, 3 columns

print(matrix)

[[1 2 2]
 [4 2 3]]


In [10]:
matrix = np.array(a)
print(matrix)

[[1 2]
 [2 4]
 [2 3]]


In [11]:
def reshape_matrix(a: list[list[int|float]], new_shape: tuple[int, int]) -> list[list[int|float]]:
	#Write your code here and return a python list after reshaping by using numpy's tolist() method
    temp_matrix = np.array(a)
    if temp_matrix.size != (new_shape[0]*new_shape[1]):
        return []
    reshaped_matrix = temp_matrix.reshape(new_shape[0],new_shape[1]).tolist()
    return reshaped_matrix

# transpose_matrix

In [12]:
def transpose_matrix(a: list[list[int|float]]) -> list[list[int|float]]:
    matrix = np.array(a)
    b = matrix.T
    return b

In [14]:
a = [[1, 2], [2, 4], [2,3]]
print(a)
print(transpose_matrix(a))

[[1, 2], [2, 4], [2, 3]]
[[1 2 2]
 [2 4 3]]


# Calculate Mean by Row or Column

In [15]:
import numpy as np
def calculate_matrix_mean(matrix: list[list[float]], mode: str) -> list[float]:
    if mode == 'column':
        means=np.mean(matrix, axis=0) #column-wise mean
    else:
        means = np.mean(matrix, axis=1) #row-wise mean
    return means

In [17]:
print(calculate_matrix_mean([[1, 2], [4, 5]], 'column'))
print(calculate_matrix_mean([[1, 2], [4, 5]], 'row'))

[2.5 3.5]
[1.5 4.5]


# Scalar Multiplication of a Matrix

In [20]:
def scalar_multiply(matrix: list[list[int|float]], scalar: int|float) -> list[list[int|float]]:
    result = np.array(matrix)*scalar
    return result

In [21]:
print(scalar_multiply([[1,2],[3,4]], 2))

[[2 4]
 [6 8]]


# cosine similarity 

In [23]:

def cosine_similarity(v1, v2):
    numerator = np.sum(np.dot(v1,v2),axis = 0)
    sqrt_sum_A = math.sqrt(np.sum(np.square(v1),axis =0))
    sqrt_sum_B = math.sqrt(np.sum(np.square(v2),axis =0))
    result = round(numerator / (sqrt_sum_A * sqrt_sum_B),3)
    return result

In [25]:
v1 = np.array([1, 2, 3]) 
v2 = np.array([2, 4, 6]) 
print(cosine_similarity(v1, v2))

v1 = np.array([1, 0, 7]) 
v2 = np.array([0, 1, 3]) 
print(cosine_similarity(v1, v2))

1.0
0.939
