In [ ]:
import numpy as np
def matrix_dot_vector(a: list[list[int|float]], b: list[int|float]) -> list[int|float]:
	# Return a list where each element is the dot product of a row of 'a' with 'b'.
	# If the number of columns in 'a' does not match the length of 'b', return -1.
	if len(a[0])!=len(b):
		return -1
	else:
		return np.dot(a,b)


# how does dot product work 

### <img src="../img/img_1.png" width="500" height="500">

In [3]:
a = [[1, 2], [2, 4]]
b = [[1, 2], [4, 5]]
np.dot(a, b)

array([[ 9, 12],
       [18, 24]])

In [6]:
a = [[1, 2], [2, 4]]
b = [[1, 2, 3], [4, 5, 6]]


np.dot(a, b)

array([[ 9, 12, 15],
       [18, 24, 30]])

## how does reshape works 
- .reshape(2, 3) You're asking NumPy to reshape the array to shape (2, 3) — i.e., 2 rows and 3 columns.
- Reshape does not change the data, only how it's grouped.
- NumPy will flatten the original matrix row-wise:
- Original data: [1, 2, 2, 4, 2, 3]

In [9]:
a = [[1, 2], [2, 4], [2,3]]
matrix = np.array(a).reshape(2, 3)  # 2 rows, 3 columns

print(matrix)

[[1 2 2]
 [4 2 3]]


In [10]:
matrix = np.array(a)
print(matrix)

[[1 2]
 [2 4]
 [2 3]]
